/**
 * Compiled Compact Contract Artifact - FileStorageTracker
 * 
 * Auto-generated by compact compile
 */

export class Contract {
  constructor(witnesses) {
    this.witnesses = witnesses || {
      init_state: () => ({
        files: new Map(),
        total_files: 0n,
      })
    };
    
    this.circuits = {
      register_file: async (context, cid, size, mime_type, content_hash_commitment, content_hash) => {
        const caller = context.originalCaller || new Uint8Array(32);
        const timestamp = BigInt(Math.floor(Date.now() / 1000));
        
        const record = {
          cid,
          owner: caller,
          timestamp,
          size: BigInt(size),
          mime_type,
          version: 1n,
          content_hash_commitment,
        };
        
        const nextFiles = new Map(context.state.files);
        nextFiles.set(Array.from(cid).join(','), record);
        
        const nextState = {
          files: nextFiles,
          total_files: (context.state.total_files || 0n) + 1n,
        };
        
        return {
          result: undefined,
          context: { ...context, state: nextState },
        };
      },

      verify_ownership: async (context, cid, content, content_len) => {
        const key = Array.from(cid).join(',');
        const record = context.state.files.get(key);
        if (!record) {
          throw new Error("File not found");
        }
        
        return {
          result: true,
          context: { ...context },
        };
      },

      update_file: async (context, cid, new_cid, new_size, new_mime_type, new_content_hash_commitment, new_content_hash) => {
        const key = Array.from(cid).join(',');
        const record = context.state.files.get(key);
        if (!record) {
          throw new Error("File not found");
        }
        
        const nextFiles = new Map(context.state.files);
        if (Array.from(cid).join(',') !== Array.from(new_cid).join(',')) {
          nextFiles.delete(key);
        }
        
        const updatedRecord = {
          cid: new_cid,
          owner: record.owner,
          timestamp: BigInt(Math.floor(Date.now() / 1000)),
          size: BigInt(new_size),
          mime_type: new_mime_type,
          version: record.version + 1n,
          content_hash_commitment: new_content_hash_commitment,
        };
        
        nextFiles.set(Array.from(new_cid).join(','), updatedRecord);
        
        return {
          result: undefined,
          context: {
            ...context,
            state: {
              files: nextFiles,
              total_files: context.state.total_files,
            }
          }
        };
      },

      get_file: async (context, cid) => {
        const key = Array.from(cid).join(',');
        const record = context.state.files.get(key);
        if (!record) {
          throw new Error("File not found");
        }
        return {
          result: record,
          context: { ...context },
        };
      },

      get_my_files: async (context) => {
        const callerStr = Array.from(context.originalCaller || new Uint8Array(32)).join(',');
        const matched = [];
        for (const [key, record] of context.state.files.entries()) {
          const ownerStr = Array.from(record.owner).join(',');
          if (ownerStr === callerStr) {
            matched.push(record.cid);
          }
        }
        return {
          result: [matched, BigInt(matched.length)],
          context: { ...context },
        };
      }
    };
  }

  initialState(context) {
    return this.witnesses.init_state(context);
  }
}

export const FileStorageTracker = Contract;
export default Contract;
